# Generated by Django 4.2.15 on 2024-12-05 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OsTyper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('oscammand', 'oscammand'), ('mathcocommand', 'mathcocommand')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OsCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=50)),
                ('command_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='echo.ostyper')),
            ],
        ),
        migrations.CreateModel(
            name='MathCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.CharField(max_length=50)),
                ('command_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='echo.ostyper')),
            ],
        ),
    ]
