# Generated by Django 4.2.15 on 2024-12-05 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('echo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='mathcommand',
            name='command_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='echo.ostyper'),
        ),
        migrations.AlterField(
            model_name='oscommand',
            name='command_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='echo.ostyper'),
        ),
        migrations.AddField(
            model_name='oscommand',
            name='paramet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='echo.parameter'),
        ),
    ]
